### PR TITLE
Add `--prefer-private-ip` argument to the `eb ssh` command

### PR DESCRIPTION
**Pull request by blampe**
*Issue #3*

*Description of changes:*

This is a quality of life improvement for anyone who'd like to run a split-tunnel VPN.

This preserves the existing behavior of the `eb ssh` command but exposes a `--prefer-private-ip` option that uses the instance's private IP before its public one.

I've included a unit test, and I've confirmed this works as expected in my environment.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by frank-parry — APPROVED** [review]
Tested against my environment- works perfectly as described

**Review by frank-parry — APPROVED** [review]

**Comment by brandonburkett** [comment]
Did this change make it in? I would like to be able to eb ssh with private IP restrictions.

**Comment by yohanthshetty** [comment]
> Did this change make it in? I would like to be able to eb ssh with private IP restrictions.

Hi @brandonburkett, Yes, the change has been merged to the master branch. Thank You.

**Comment by alisson276** [comment]
It would be nice having this merged!

**Comment by blampe** [comment]
Closing this since I no longer use EB.

> > Did this change make it in? I would like to be able to eb ssh with private IP restrictions.
> 
> Hi @brandonburkett, Yes, the change has been merged to the master branch. Thank You.

@yohanthshetty they were asking if this fix had been released yet, and it [has not](https://github.com/aws/aws-elastic-beanstalk-cli/blob/5dd34def398a223554c3980b741d15f251f6e605/ebcli/operations/sshops.py#L94-L100).

**Pull request closed without merging**
